# Generated by Django 5.2.1 on 2025-05-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
