name: Django CI

# Run workflow on pushes to main branch or pull requests targeting main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Optional: if your tests require a database service like postgres or mysql, add here
      # For now, using Django's default SQLite, so no DB service is required.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test

      # Optional: upload test reports/artifacts here if needed
